<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<body>
    <script>
        /**
         * 如果 onFulfilled 返回了一个 promise，
         * then 的返回值就会被 Promise resolved 或者 rejected。
         */
        function resolveLater(resolve, reject) {
            setTimeout(function () {
                resolve(10);
            }, 1000);
        }

        function rejectLater(resolve, reject) {
            setTimeout(function () {
                reject(new Error('Error'));
            }, 1000);
        }

        var p1 = Promise.resolve('foo');
        var p2 = p1.then(function () {
            return new Promise(resolveLater);
        });
        p2.then(function (v) {
            console.log('resolved', v);
        }, function (e) {
            console.error('rejected', e);
        });

        var p3 = p1.then(function () {
            return new Promise(rejectLater);
        });
        p3.then(function (v) {
            console.log('resolved', v);
        }, function (e) {
            console.error('rejected', e);
        });

        /**
         * 打印结果
         * 34行 resolved 10
         * 45行 打印25行创建的错误 rejected Error: Error at 2-9.onFulfilled 返回了一个 promise.html:25
         */
    </script>
</body>

</html>